# Generated by Django 5.1 on 2024-08-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='contentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
