# Generated by Django 5.1 on 2024-09-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_contentimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimages',
            name='profile_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
